"""Opt-in OCR regression on a synthetic Korean+English lecture slide.

Enable with VIDEO2MD_INTEGRATION=1. Requires ocrmac / macOS Vision.

The fixture is generated by tests/fixtures/ocr/make_slide.py.
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest

from video2md.ocr import recognize_frame

INTEGRATION_GATED = pytest.mark.skipif(
    os.environ.get("VIDEO2MD_INTEGRATION") != "1",
    reason="set VIDEO2MD_INTEGRATION=1 to run",
)

SAMPLE = Path(__file__).resolve().parent.parent / "fixtures" / "ocr" / "korean_slide.jpg"

KOREAN_NEEDLES = (
    "화면 OCR 샘플",
    "한국어",
    "English",
    "정렬",
)


@INTEGRATION_GATED
def test_sample_slide_keeps_korean_with_default_ocr():
    assert SAMPLE.is_file()
    lines = recognize_frame(SAMPLE, language=None, confidence=0.30)
    text = "\n".join(line.text for line in lines)
    missing = [n for n in KOREAN_NEEDLES if n not in text]
    assert not missing, f"missing {missing} in OCR text:\n{text}"
    assert sum("가" <= c <= "힣" for c in text) >= 50
